name: First Action

on:
  push:
    branches:
      - main
      - feature/**
  pull_request:
    branches:
      - main
    types:
      - opened
      - edited
      - synchronize

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: First Step
        shell: bash
        run: |
          echo "running first step"
