name: First Action

on:
  push:
    branches:
      - 'feature/**'
  pull_request:
    branches:
      - main
    types: [ opened , synchronize , edited ]

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: First Step
        shell: bash
        run: |
          echo "running first step"
