name: First Action

on:
  push:
    branches:
      - 'feature/**'
  pull_request:
    branches:
      - main
    types: [ opened , synchronize , edited ]

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: First Step
        shell: bash
        run: |
          echo "running first step"

name: 🔍 Test FTP connection
on: workflow_dispatch

jobs:
  test-connection:
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Checkout
        uses: actions/checkout@v4

      - name: 🧪 Test FTP Connection
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          dry-run: true