name: 🔍 Test FTP connection
on: workflow_dispatch

jobs:
  test-connection:
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Checkout
        uses: actions/checkout@v4
      
      - name: 🔐 Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: unnecessary_with_strict_false
      
      - name: 🛰️ Test connection and list directories
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "echo '✅ Conexión exitosa con el usuario: ' && whoami && ls -F public_html"

      #- name: 🚀 Rsync Deploy
      #  run: |
      #    rsync -avz -e "ssh -o StrictHostKeyChecking=no" \
      #    --exclude '.git*' \
      #    --exclude '.github*' \
      #    ./ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/home/${{ secrets.SSH_USER }}/public_html/