name: 🔍 Test FTP connection
on: workflow_dispatch

jobs:
  test-connection:
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Checkout
        uses: actions/checkout@v4
      
      - name: 🚀 Copiar archivos vía SCP
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          source: "."
          target: "/home/betgallos/testing.betgallos.com/v2"
          rm: false